### ISSUE TITLE
what's the meaning of computing the new_lr with emb_dim？

### ISSUE THREAD

**Issue by XingLuxi** [ne7ermore/torch_light#3]
https://github.com/ne7ermore/torch_light/blob/6ec234c1e4db26404c8ef32c51c0050628c9bf64/vae-nlg/optim.py#L24

**Comment by ne7ermore** [comment]
It comes from paper: Attention Is All You Need - 5.3 Optimizer
You may get more info from this link  https://arxiv.org/pdf/1706.03762.pdf
