### ISSUE TITLE
Problems while running facial-beauty-prediction

### ISSUE THREAD

**Issue by iblh** [ne7ermore/torch_light#6]
Hi, where can I download the images and verification in the following paths:
```
/Users/nevermore/code/fuel/SCUT-FBP5500_v2/Images
 
/Users/nevermore/code/fuel/SCUT-FBP5500_v2/train_test_files/5_folders_cross_validations_files/cross_validation_1
```

[facial-beauty-prediction/data/images](https://github.com/ne7ermore/torch_light/blob/master/facial-beauty-prediction/data/images)
[facial-beauty-prediction/data/validation](https://github.com/ne7ermore/torch_light/blob/master/facial-beauty-prediction/data/validation)

**Comment by ne7ermore** [comment]
https://github.com/HCIILAB/SCUT-FBP5500-Database-Release
